//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int Clave_M { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<int> Clave_R1 { get; set; }
        public Nullable<int> Clave_D1 { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
